// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_Data_API.DataLayer;

#nullable disable

namespace Movie_Data_API.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsActor_ID")
                        .HasColumnType("int");

                    b.Property<int>("Movies_ID")
                        .HasColumnType("int");

                    b.HasKey("ActorsActor_ID", "Movies_ID");

                    b.HasIndex("Movies_ID");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresGenre_ID")
                        .HasColumnType("int");

                    b.Property<int>("Movies_ID")
                        .HasColumnType("int");

                    b.HasKey("GenresGenre_ID", "Movies_ID");

                    b.HasIndex("Movies_ID");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Actor", b =>
                {
                    b.Property<int>("Actor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Actor_ID"));

                    b.Property<string>("Actor_Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birth_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Actor_ID");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Actor_ID = 1,
                            Actor_Lastname = "Downey Jr",
                            Actor_Name = "Robert",
                            Birth_Date = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Actor_ID = 2,
                            Actor_Lastname = "Johansson",
                            Actor_Name = "Scarlett",
                            Birth_Date = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Actor_ID = 3,
                            Actor_Lastname = "Washington",
                            Actor_Name = "Denzel",
                            Birth_Date = new DateTime(1954, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Actor_ID = 4,
                            Actor_Lastname = "Stone",
                            Actor_Name = "Emma",
                            Birth_Date = new DateTime(1988, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Genre", b =>
                {
                    b.Property<int>("Genre_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Genre_ID"));

                    b.Property<string>("Genre_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Genre_ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Genre_ID = 1,
                            Genre_Name = "Action"
                        },
                        new
                        {
                            Genre_ID = 2,
                            Genre_Name = "Comedy"
                        },
                        new
                        {
                            Genre_ID = 3,
                            Genre_Name = "Drama"
                        },
                        new
                        {
                            Genre_ID = 4,
                            Genre_Name = "Sci-Fi"
                        },
                        new
                        {
                            Genre_ID = 5,
                            Genre_Name = "Horror"
                        },
                        new
                        {
                            Genre_ID = 6,
                            Genre_Name = "Romance"
                        },
                        new
                        {
                            Genre_ID = 7,
                            Genre_Name = "Thriller"
                        },
                        new
                        {
                            Genre_ID = 8,
                            Genre_Name = "Fantasy"
                        },
                        new
                        {
                            Genre_ID = 9,
                            Genre_Name = "Animation"
                        },
                        new
                        {
                            Genre_ID = 10,
                            Genre_Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Movie", b =>
                {
                    b.Property<int>("Movies_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Movies_ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Movies_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Review", b =>
                {
                    b.Property<int>("Review_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Review_ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Movie_ID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Review_ID");

                    b.HasIndex("Movie_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Role", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Role_ID = 1,
                            Role_Name = "Admin"
                        },
                        new
                        {
                            Role_ID = 2,
                            Role_Name = "User"
                        });
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role_ID")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.HasIndex("Role_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Movie_Data_API.DataLayer.Entities.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsActor_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movie_Data_API.DataLayer.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("Movies_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("Movie_Data_API.DataLayer.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenre_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movie_Data_API.DataLayer.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("Movies_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Movie", b =>
                {
                    b.HasOne("Movie_Data_API.DataLayer.Entities.User", "User")
                        .WithMany("Movies")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Review", b =>
                {
                    b.HasOne("Movie_Data_API.DataLayer.Entities.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("Movie_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Data_API.DataLayer.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.User", b =>
                {
                    b.HasOne("Movie_Data_API.DataLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Movie", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Movie_Data_API.DataLayer.Entities.User", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
